// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAxA-6PExkOjzTpWFUJTeC4Eo32QqDj3M',
    appId: '1:768523052619:android:14ade1599ec74579bf4fce',
    messagingSenderId: '768523052619',
    projectId: 'evently-260dc',
    storageBucket: 'evently-260dc.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvzmwSyQXTwnbT-Z36inXw7u766F5lUyA',
    appId: '1:768523052619:ios:8a282d6333e4aacbbf4fce',
    messagingSenderId: '768523052619',
    projectId: 'evently-260dc',
    storageBucket: 'evently-260dc.firebasestorage.app',
    androidClientId: '768523052619-lo39m8q45ng3ogqdvpge4f9bng4a71ou.apps.googleusercontent.com',
    iosClientId: '768523052619-9cmhb4mitdborp6iv98r8452qirr19ms.apps.googleusercontent.com',
    iosBundleId: 'com.example.evently',
  );
}
